export default {
  tab_1: require('../img/tab_1.png'),
  tab_1_h: require('../img/tab_1_h.png'),
  tab_2: require('../img/tab_2.png'),
  tab_2_h: require('../img/tab_2_h.png'),
  tab_3: require('../img/tab_3.png'),
  tab_3_h: require('../img/tab_3_h.png'),
  tab_4: require('../img/tab_4.png'),
  tab_4_h: require('../img/tab_4_h.png'),
  eos: require('../img/eos.png'),
  home_bg: require('../img/home_bg.png'),
  qr: require('../img/qr.png'),
  scan: require('../img/scan.png'),
  add: require('../img/add.png'),
  aab1: require('../img/aab1.png'),
  aab2: require('../img/aab2.png'),
  Agent: require('../img/Agent.png'),
  AgentInfo_bg: require('../img/AgentInfo_bg.png'),
  imvote:require('../img/imvote.png'),
  wallet: require('../img/wallet.png'),
  fav: require('../img/fav.png'),
  fav_h: require('../img/fav_h.png'),
  tag:require('../img/tag.png'),
  shareBg:require('../img/share_bg.png'),
  qrcode:require('../img/qrcode.png'),
  phone:require('../img/phone.png'),
  refresh:require('../img/refresh.png'),
  logo:require('../img/logo1.png'),
  signed:require('../img/signed.png'),  
  a:require('../img/a.png'),
  b:require('../img/b.png'),
  c:require('../img/c.png'),
  candy:require('../img/candy.png'),
  cmy_db:require('../img/cmy_db.png'),
  cmy_gzh:require('../img/cmy_gzh.png'),
  cmy_qq:require('../img/cmy_qq.png'),
  cmy_wb:require('../img/cmy_wb.png'),
  cmy_wx:require('../img/cmy_wx.png'),
  cmyhead:require('../img/cmyhead_by.png'),
  d:require('../img/d.png'),
  link:require('../img/link.png'),
  inb:require('../img/inb.png'),
  integral_bg:require('../img/integral_bg.png'),
  up:require('../img/up.png'),
  up_h:require('../img/up_h.png'),
  down:require('../img/down.png'),
  down_h:require('../img/down_h.png'),
  share:require('../img/share.png'),
  share_banner:require('../img/share_banner.png'),
  share_bottom:require('../img/share_bottom.png'),
  share_wx:require('../img/share_wx.png'),
  share_qq:require('../img/share_qq.png'),
  share_Size:require('../img/share_Size.png'),
  share_img:require('../img/share_img.png'),
  share_pyq:require('../img/share_pyq.png'),
  share_i:require('../img/share_i.png'),
  point_empty:require('../img/point_empty.png'),
  point_full:require('../img/point_full.png'),
  al:require('../img/al.png'),
  turn_out:require('../img/turn_out.png'),
  shift_to:require('../img/shift_to.png'),
  wallet_1:require('../img/wallet_1.png'),
  xin0:require('../img/xin0.png'),
  xin1:require('../img/xin1.png'),
  vote:require('../img/vote.png'),
  
  votea:require('../img/votea.png'),
  voteb:require('../img/voteb.png'),
  votec:require('../img/votec.png'),
  votea_bj:require('../img/votea_bj.png'),
  voteb_bj:require('../img/voteb_bj.png'),
  votec_bj:require('../img/votec_bj.png'),
  vote_h:require('../img/vote_h.png'),
  vote_node:require('../img/vote_node.png'),
  Tick:require('../img/Tick.png'),
  Tick_h:require('../img/Tick_h.png'),
  Magnifier:require('../img/Magnifier.png'),
  nash:require('../img/nash.png'),
  Invitation_vote:require('../img/Invitation_vote.png'),
}
